biblioth-que-master/config/routes.rb
Rails.application.routes.draw do

  resources :livres
  devise_for :users

 
root 'welcome#home'
  # get 'welcome' => 'welcome#home'
  # The priority is b
  #ased upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

biblioth-que-master/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :livres
end

biblioth-que-master/app/models/livre.rb
class Livre < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
end

biblioth-que-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :livres
         has_many :category

end

biblioth-que-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
end

biblioth-que-master/app/controllers/livres_controller.rb
class LivresController < ApplicationController
  before_action :set_livre, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /livres
  # GET /livres.json
  def index
    @livres = Livre.all
  end

  # GET /livres/1
  # GET /livres/1.json
  def show
  end

  # GET /livres/new
  def new
    @livre = Livre.new
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # GET /livres/1/edit
  def edit
      @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # POST /livres
  # POST /livres.json
  def create
    @livre = Livre.new(livre_params)
    @livre.category_id = params[:category_id]

    respond_to do |format|
      if @livre.save
        format.html { redirect_to @livre, notice: 'Livre a été bien créer.' }
        format.json { render :show, status: :created, location: @livre }
      else
        format.html { render :new }
        format.json { render json: @livre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livres/1
  # PATCH/PUT /livres/1.json
  def update
    @livre.category_id = params[:category_id]
    respond_to do |format|
      if @livre.update(livre_params)
        format.html { redirect_to @livre, notice: 'Livre was successfully updated.' }
        format.json { render :show, status: :ok, location: @livre }
      else
        format.html { render :edit }
        format.json { render json: @livre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livres/1
  # DELETE /livres/1.json
  def destroy
    @livre.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Livre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livre
      @livre = Livre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livre_params
      params.require(:livre).permit(:titre, :auteur, :description, :url, :prix, :category_id)
    end
end

biblioth-que-master/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  	@livres = Livre.all
  end
end

biblioth-que-master/app/helpers/application_helper.rb
module ApplicationHelper
end

biblioth-que-master/app/helpers/livres_helper.rb
module LivresHelper
end

biblioth-que-master/app/helpers/welcome_helper.rb
module WelcomeHelper
end

biblioth-que-master/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to(image_tag('logo.png'), root_path)  %>
          </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          <% if !user_signed_in? %>
          <li><%= link_to "CONNEXION", new_user_registration_path, class: "btn btn-default" %> </li>
          <% else %>
          <li><%= link_to "DECONNEXION", destroy_user_session_path, method: :delete, class: "btn btn-default" %> </li>
          <% end %>
           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Créer<span class="caret"></span></a>
              <ul class="dropdown-menu">
                
                <li><%= link_to "Livre", new_livre_path %> </li>
                
              </ul>
            </li>
         
          </ul>
          
        </div><!--/.nav-collapse -->
         

      </div>
    </nav>

biblioth-que-master/app/views/layouts/_listleft.html.erb
<div class="list-left" id="dashboard">
  <div class="element">
			<span class="glyphicon glyphicon-home" aria-hidden="true"></span> <%= link_to "Home", root_path %>
  </div>
  <div class="element">
              <span class="glyphicon glyphicon-tags" aria-hidden="true"></span> <%= link_to "Tags", '#' %>
  </div>
  <div class="element">
				<span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span> <%= link_to "videos", videos_path %> (<%= @videos.count %>) 

  </div>
  <div class="element">
        <span class="glyphicon glyphicon-magnet" aria-hidden="true"></span> <%= link_to "Links", links_path %> (<%= @links.count %>)

  </div>

  <div class="element">
        <span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span> <%= link_to "Post", posts_path %> (<%= @posts.count %> )

  </div>

   <div class="element">
        <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> <%= link_to "Location", links_path %> (5)

  </div>

    <div class="element">
        <span class="glyphicon glyphicon-picture" aria-hidden="true"></span> <%= link_to "Picture", links_path %> (8)

  </div>

  <div class="element">
        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> <%= link_to "calander", links_path %> (2)

  </div>
</div>

biblioth-que-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BooksCollection</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<% flash.each do |name, msg| %>
<%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>

<%= yield %>	

</body>
</html>

biblioth-que-master/app/views/livres/_form.html.erb
<%= simple_form_for(@livre) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Choisir catégorie") %>
    <%= f.input :titre %>
    <%= f.input :auteur %>
    <%= f.input :description %>
    <%= f.input :url %>
    <%= f.input :prix %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

biblioth-que-master/app/views/livres/edit.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>Modifier Le Livre</h1>

<%= simple_form_for(@livre) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  <p><strong>category</strong></p>
    <%= f.select :category_id, @categories %>
    <%= f.input :titre %>
    <%= f.input :auteur %>
    <%= f.input :description %>
    <%= f.input :url %>
    <%= f.input :prix %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Modifier Livre" %>
  </div>
<% end %>

<%= link_to 'Afficher', @livre %> |
<%= link_to 'Retourner', root_path %>
</div>

biblioth-que-master/app/views/livres/new.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>Nouveau Livre</h1>
<%= simple_form_for(@livre) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Choisir catégorie") %>
    <%= f.input :titre %>
    <%= f.input :auteur %>
    <%= f.input :description %>
    <%= f.input :url %>
    <%= f.input :prix %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Ajouter Livre" %>
  </div>
<% end %>

<%= link_to 'Retourner', root_path %>
</div>

biblioth-que-master/app/views/livres/show.html.erb
<div class="col-md-6 col-md-offset-3">

<p id="notice"><%= notice %></p>
  <h1>Titre: <%= @livre.titre %></h1>
  
</p>


  <h1>Auteur: <%= @livre.auteur %></h1>
  
</p>
<p>  <h1>Categorie: <%= @livre.category.name %></h1></p>

  <h1>Description:</h1> 
  <p><%= @livre.description %></p> 
  
</p>



  <h1>Url: <%= @livre.url %>  </h1>
  
</p>


  <h1>Prix: <%= @livre.prix %> €</h1>
 

<p> <%= link_to 'Modifier', edit_livre_path(@livre), class: "btn btn-primary" %> |
<%= link_to 'Supprimer', @livre, method: :delete, data: { confirm: 'Vous voulais supprimer le livre?' }, class: "btn btn-default" %></p>
<%= link_to 'Retourner', root_path, class: "btn btn-default" %>
</div>

biblioth-que-master/app/views/welcome/home.html.erb
<div class="landing-page">


<header>
	
	
</header>
<!-- si la variable livres retourne null  --> 
 <% if @livres.blank? %>
   <div class="jumbotron">
      <div class="container">
        <h1>Bienvenue dans votre bibliothèque spécialisée !!</h1>
     <p>Plus clair, plus pratique, plus convivial, le site LivresApp est une bibliothèque en ligne, celui-ci fait la part belle aux ouvrages .
	Ainsi, en cliquant par exemple sur l'onglet "Créer", puis selectionner la partie Livre, vous arrivez directement au rayon concernant à la creation d'un nouveau livre, mais tous cela n'ai fait qu'après une bonne authentification.</p> 
	<strong>Admin</strong>

  <p> <%= link_to "Créer un livre ..", new_livre_path, class: "btn btn-primary btn-lg" %></p>
      </div>
    </div>
    <!--sinon il va afficher tous les livres-->
 <% else %>
 <h1>Librairie</h1>
 <div class="container">
	<div class="row">
	<% @livres.each do |livre| %>
	        <div class="col-lg-4">
	    <div class="thumbnail">
	    <img src="http://www.idboox.com/wp-content/uploads/2011/03/Harlan_Coben_Ebooks-IDBOOX.jpg" alt="">
	    </div>
	        <h2 style="color: blue;">Titre: <%= livre.titre %> </h2>
	        <h3>Categorie: <%= livre.category.name %></h3>
	        <h3>Auteur: <%= livre.auteur %></h3>
	        <h3>Description :</h3> <p> <%= truncate(livre.description, :length => 150)  %></p>

	        <h3>Prix: <%= livre.prix %> €</h3>
	        <p> <%= link_to 'Acceder', livre, class: "btn btn-primary" %></p>      
	      </div>
	    <% end %>
	  </div>
	  </div>
 <% end %>
<footer class="footer">
      <div class="container">
        <p class="text-muted">2016 créer par Sabri T.</p>
      </div>
    </footer>

</div>